/**
 * Cal.com booking webhook handler.
 * Receives BOOKING_CREATED events from Cal.com and fires server-side
 * conversion events to GA4 (via Measurement Protocol), Google Ads
 * (Enhanced Conversions API), and Meta (Conversions API).
 *
 * Endpoint: https://www.bahri.studio/api/cal-booking
 *
 * REQUIRED env vars (set in Vercel dashboard → Settings → Environment Variables):
 *   - CAL_WEBHOOK_SECRET    Signing secret generated by Cal.com when creating the webhook
 *   - GA4_MEASUREMENT_ID    G-1Z4HFE6DZR
 *   - GA4_API_SECRET        Measurement Protocol API secret (GA4 → Admin → Data Streams → Web → Measurement Protocol API secrets → Create)
 *
 * OPTIONAL env vars (set when ready):
 *   - GADS_CONVERSION_ID       e.g. AW-1234567890
 *   - GADS_CONVERSION_LABEL    e.g. abcDEF12345
 *   - GADS_DEVELOPER_TOKEN     For Google Ads API direct calls (advanced)
 *   - META_PIXEL_ID            Your Meta Pixel ID
 *   - META_ACCESS_TOKEN        System user token from Meta Business Manager
 *
 * Cal.com webhook payload reference:
 *   https://cal.com/docs/core-features/webhooks
 */

import crypto from 'node:crypto';

const AUDIT_VALUE_EUR = 1500;          // baseline Audit price for conversion value
const AUDIT_CURRENCY  = 'EUR';

export default async function handler(req, res) {
  // Cal.com sends POST. Reject everything else.
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Vercel parses JSON automatically, but we need the raw body for HMAC.
  // Vercel exposes the parsed body on req.body. To verify signature, reconstruct.
  const payload = req.body;
  const rawBody = JSON.stringify(payload);

  // 1. Verify Cal.com signature (X-Cal-Signature-256 header)
  const secret = process.env.CAL_WEBHOOK_SECRET;
  if (!secret) {
    console.error('CAL_WEBHOOK_SECRET env var missing');
    return res.status(500).json({ error: 'Server misconfigured' });
  }
  const signature = req.headers['x-cal-signature-256'];
  if (!signature) {
    console.warn('Missing X-Cal-Signature-256 header');
    return res.status(401).json({ error: 'Missing signature' });
  }
  const expected = crypto.createHmac('sha256', secret).update(rawBody).digest('hex');
  if (!crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) {
    console.warn('Invalid Cal.com signature');
    return res.status(401).json({ error: 'Invalid signature' });
  }

  // 2. Only process BOOKING_CREATED events. Ignore the rest (CANCELLED, RESCHEDULED, etc.)
  if (payload.triggerEvent !== 'BOOKING_CREATED') {
    return res.status(200).json({ ok: true, ignored: payload.triggerEvent });
  }

  // 3. Extract booking data we'll use for tracking
  const booking = payload.payload || {};
  const inviteeEmail = booking.attendees?.[0]?.email || booking.responses?.email?.value || '';
  const inviteeName  = booking.attendees?.[0]?.name  || booking.responses?.name?.value  || '';
  const eventTypeId  = booking.eventType?.id || booking.eventTypeId || '';
  const startTime    = booking.startTime || '';
  const bookingId    = booking.uid || booking.id || crypto.randomUUID();

  // Hash PII for ad-platform Enhanced Conversions
  const hashedEmail = inviteeEmail ? sha256(inviteeEmail.trim().toLowerCase()) : '';

  console.log('[cal-booking] new booking', { bookingId, inviteeEmail, eventTypeId, startTime });

  // 4. Fire conversion events in parallel
  const results = await Promise.allSettled([
    fireGa4Event({ bookingId, inviteeEmail, eventTypeId, startTime }),
    fireGoogleAdsConversion({ bookingId, hashedEmail, startTime }),
    fireMetaCAPI({ bookingId, inviteeEmail, hashedEmail, inviteeName, startTime, ip: req.headers['x-forwarded-for'], userAgent: req.headers['user-agent'] }),
  ]);

  const summary = {
    ga4:        formatResult(results[0]),
    google_ads: formatResult(results[1]),
    meta:       formatResult(results[2]),
  };
  console.log('[cal-booking] dispatch summary', summary);

  return res.status(200).json({ ok: true, booking_id: bookingId, dispatched: summary });
}

/* ──────────────────────────  HELPERS  ────────────────────────── */

function sha256(str) {
  return crypto.createHash('sha256').update(str).digest('hex');
}

function formatResult(r) {
  if (r.status === 'fulfilled') return { ok: true, info: r.value };
  return { ok: false, error: String(r.reason?.message || r.reason) };
}

/* ──────────────────────────  GA4 (Measurement Protocol)  ────────────────────────── */

async function fireGa4Event({ bookingId, inviteeEmail, eventTypeId, startTime }) {
  const measurementId = process.env.GA4_MEASUREMENT_ID;
  const apiSecret     = process.env.GA4_API_SECRET;
  if (!measurementId || !apiSecret) {
    return 'skipped: GA4_MEASUREMENT_ID or GA4_API_SECRET missing';
  }

  const url = `https://www.google-analytics.com/mp/collect?measurement_id=${encodeURIComponent(measurementId)}&api_secret=${encodeURIComponent(apiSecret)}`;

  const body = {
    client_id: bookingId,
    user_id:   inviteeEmail || undefined,
    events: [{
      name: 'book_appointment',  // matches Google Ads BOOK_APPOINTMENT conversion (imported as conversion_event_book_appointment)
      params: {
        booking_id:        bookingId,
        event_type_id:     eventTypeId,
        event_start_time:  startTime,
        currency:          AUDIT_CURRENCY,
        value:             AUDIT_VALUE_EUR,
        engagement_time_msec: 100,
      },
    }, {
      name: 'generate_lead',  // GA4 native event for Google Ads lead-gen optimization
      params: {
        currency:          AUDIT_CURRENCY,
        value:             AUDIT_VALUE_EUR,
        booking_id:        bookingId,
        engagement_time_msec: 100,
      },
    }, {
      name: 'calendly_booking_complete',  // legacy event kept for historical GA4 reports / GTM compatibility
      params: {
        booking_id:        bookingId,
        event_type_id:     eventTypeId,
        event_start_time:  startTime,
        currency:          AUDIT_CURRENCY,
        value:             AUDIT_VALUE_EUR,
        engagement_time_msec: 100,
      },
    }],
  };

  const resp = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  // GA4 MP returns 204 No Content on success
  return `status ${resp.status}`;
}

/* ──────────────────────────  Google Ads (Enhanced Conversions for Leads)  ────────────────────────── */

async function fireGoogleAdsConversion({ bookingId, hashedEmail, startTime }) {
  const conversionId    = process.env.GADS_CONVERSION_ID;     // e.g. AW-1234567890
  const conversionLabel = process.env.GADS_CONVERSION_LABEL;  // e.g. abcDEF12345
  if (!conversionId || !conversionLabel) {
    return 'skipped: GADS_CONVERSION_ID or GADS_CONVERSION_LABEL missing';
  }

  // Server-side Google Ads conversion via the Ads Conversion Tracking endpoint.
  // For a full Google Ads API integration you'd need a developer token + OAuth flow.
  // Easier path: use the offline conversion adjustments via the Conversion Linker
  // which Google Ads supports natively when GTM Conversion Linker is set up.
  //
  // The cleanest setup is:
  //   1. Set up a Google Ads conversion action in your account
  //   2. Use the conversion ID/label in your GTM Google Ads Conversion tag
  //      with the trigger Custom Event = calendly_booking_complete
  //   3. The GTM tag fires off the GA4 event when MP delivers it
  //
  // For a true server-side fire (recommended once you have the developer token),
  // implement the Google Ads API uploadOfflineConversion call here.
  return `placeholder: configure GADS_CONVERSION_ID + label, then upgrade to Google Ads API call (requires developer token)`;
}

/* ──────────────────────────  Meta Conversions API (Schedule event)  ────────────────────────── */

async function fireMetaCAPI({ bookingId, inviteeEmail, hashedEmail, inviteeName, startTime, ip, userAgent }) {
  const pixelId     = process.env.META_PIXEL_ID;
  const accessToken = process.env.META_ACCESS_TOKEN;
  if (!pixelId || !accessToken) {
    return 'skipped: META_PIXEL_ID or META_ACCESS_TOKEN missing';
  }

  const url = `https://graph.facebook.com/v19.0/${encodeURIComponent(pixelId)}/events`;

  const body = {
    data: [{
      event_name: 'Schedule',         // Meta standard event name for booked appointments
      event_time: Math.floor(Date.now() / 1000),
      action_source: 'website',
      event_id: bookingId,            // for deduplication if browser pixel also fires
      event_source_url: 'https://www.bahri.studio/book.html',
      user_data: {
        em: hashedEmail ? [hashedEmail] : undefined,
        client_ip_address: ip || undefined,
        client_user_agent: userAgent || undefined,
      },
      custom_data: {
        currency:        AUDIT_CURRENCY,
        value:           AUDIT_VALUE_EUR,
        content_type:    'product',
        content_ids:     ['audit_15min_call'],
        content_name:    '15-min Paid Media Audit',
        booking_id:      bookingId,
        event_start_time: startTime,
      },
    }],
    access_token: accessToken,
  };

  const resp = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  const json = await resp.json();
  return `status ${resp.status}, fbtrace_id ${json.fbtrace_id || 'n/a'}, events_received ${json.events_received ?? 'n/a'}`;
}
